manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob                          # ← add this
      url-base: https://github.com/urob
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: Cyboard-DigitalTailor
      url-base: https://github.com/Cyboard-DigitalTailor
  projects:
    - name: zmk
      remote: urob                        # ← was zmkfirmware
      revision: main                      # ← was v0.3
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main                      # ← was zmk-0.3, update for urob compat
  self:
    path: config
