CONFIG_SMART_RGBLED_WIDGET=y


CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y

#layer 0: off
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=0

#layer 1: yellow
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=3

#layer 2: green
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=2

#layer 3: blue
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=4

#layer 4: cyan
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=6

#layer 5: red
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=1

#layer 6: red
CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=1
