CONFIG_SMART_RGBLED_WIDGET=y

CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=n
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=0

CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=90
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_HIGH=4         # blue

CONFIG_RGBLED_WIDGET_BATTERY_COLOR_MEDIUM=2       # green

CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=40
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_LOW=3          # yellow

CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=15
CONFIG_RGBLED_WIDGET_BATTERY_COLOR_CRITICAL=1     # red
